Repository radiantearth/stac-spec, pull requests merged in 2018-08, with the labels that each got.

#180 Add examples and suggestions for mime types
  json-spec/json-spec.md
Labels: should-have

#172 adding /stac catalog entry
  api-spec/STAC-standalone.yaml
Labels: must-have

#167 Add query support
  api-spec/STAC-fragment.yaml
  api-spec/STAC-query.yaml
  api-spec/STAC-standalone.yaml
  api-spec/definitions/STAC-query.yaml
  api-spec/definitions/STAC-standalone.yaml
  api-spec/definitions/WFS3core+STAC.yaml
  api-spec/definitions/WFS3core.fragment.yaml
  api-spec/extensions/fields.fragment.yaml
  api-spec/extensions/query.fragment.yaml
  api-spec/extensions/sorting.fragment.yaml
  api-spec/package-lock.json
  api-spec/package.json
  package-lock.json
Labels: major, must-have
