Repository radiantearth/stac-spec, pull requests merged in 2018-10, with the labels that each got.

#274 Improvements to STAC Start End (Date)time Extension
  extensions/README.md
  extensions/datetime-range/example-video.json
  extensions/datetime-range/schema.json
  extensions/datetime-range/stac-datetime-range-spec.md
  extensions/stac-start-end-datetime-spec.md
Labels: should-have

#277 Move eo extension
  extensions/README.md
  extensions/eo/README.md
  extensions/eo/example-landsat8.json
  extensions/eo/json-schema.json
  extensions/examples/L1T-collection.json
  extensions/examples/landsat8-merged.json
  extensions/examples/landsat8-sample.json
  extensions/stac-collection-spec.md
Labels: must-have

#271 #257: Update OpenAPI definition to catalog / dataset definition
  api-spec/STAC-query.yaml
  api-spec/STAC-standalone.yaml
  api-spec/WFS3core+STAC.yaml
  api-spec/definitions/STAC-collections.fragment.yaml
  api-spec/definitions/STAC-standalone.yaml
  api-spec/definitions/WFS3core+STAC.yaml
  api-spec/definitions/WFS3core.fragment.yaml
  api-spec/package.json
  catalog-spec/catalog-spec.md
  catalog-spec/json-schema/catalog.json
  dataset-spec/dataset-spec.md
  dataset-spec/examples/sentinel2.json
  dataset-spec/json-schema/dataset.json
  extensions/transaction/WFS3core+STAC+extensions.yaml
  extensions/transaction/WFS3core+STAC+transaction-merge.yaml
  extensions/transaction/package-lock.json
  extensions/transaction/package.json
  extensions/transaction/transaction-fragment.yaml
  item-spec/item-spec.md
  item-spec/json-schema/stac-item.json
Labels: must-have

#275 replace collections extension with commons extension
  extensions/README.md
  extensions/commons/README.md
  extensions/commons/examples/landsat-collection.json
  extensions/commons/examples/landsat-item.json
Labels: must-have

#280 #260: Rename 'Dataset extension' to 'Collection extension' + other improvements
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  api-spec/README.md
  api-spec/STAC-query.yaml
  api-spec/STAC-standalone.yaml
  api-spec/WFS3core+STAC.yaml
  api-spec/definitions/STAC-collections.fragment.yaml
  api-spec/definitions/STAC-standalone.yaml
  api-spec/wfs-stac.md
  catalog-spec/README.md
  catalog-spec/catalog-recommendations.md
  catalog-spec/catalog-spec.md
  collection-spec/README.md
  collection-spec/collection-spec.md
  collection-spec/examples/sentinel2.json
  collection-spec/json-schema/collection.json
  dataset-spec/README.md
  dataset-spec/dataset-spec.md
  extensions/README.md
  extensions/commons/README.md
  extensions/datetime-range/README.md
  extensions/eo/README.md
  extensions/eo/schema.json
  extensions/examples/README.md
  extensions/scientific/README.md
  extensions/scientific/example-merraclim.json
  extensions/scientific/schema.json
  extensions/stac-collection-spec.md
  extensions/transaction/README.md
  extensions/transaction/WFS3core+STAC+extensions.yaml
  how-to-help.md
  item-spec/README.md
  item-spec/examples/CBERS_4_MUX_20170528_090_084_L2.json
  item-spec/examples/README.md
  item-spec/examples/digitalglobe-sample.json
  item-spec/examples/landsat8-sample.json
  item-spec/examples/planet-sample.json
  item-spec/examples/sample-full.json
  item-spec/examples/sample.json
  item-spec/examples/sentinel2-sample.json
  item-spec/item-spec.md
  principles.md
  roadmap.md
  validation/README.md
  validation/package.json
Labels: must-have

#290 Relation type consistency across specs
  catalog-spec/catalog-spec.md
  collection-spec/collection-spec.md
Labels: bug, must-have

#291 Minor changes and typos
  collection-spec/collection-spec.md
  item-spec/item-spec.md
Labels: must-have

#292 Fixed north/south inconsistencies inherited from WFS3.
  api-spec/WFS3core+STAC.yaml
  api-spec/definitions/WFS3core.fragment.yaml
  collection-spec/collection-spec.md
  collection-spec/examples/sentinel2.json
  extensions/transaction/WFS3core+STAC+extensions.yaml
Labels: must-have

#317 Document 'title' as a commonly-used property
  item-spec/item-spec.md
Labels: proposed

#332 Fixed link to the UML diagram, which is invalid on master.
  README.md
Labels: bug, must-have

#333 Removed null valued fields from examples
  extensions/eo/README.md
Labels: bug, should-have

#331 Allow null for eo:epsg in JSON schema
  extensions/eo/schema.json
Labels: bug, must-have

#328 Fixes to the changelog
  CHANGELOG.md
Labels: should-have
