Repository radiantearth/stac-spec, pull requests merged in 2019-03, with the labels that each got.

#360 JSON Schema draft-07
  catalog-spec/json-schema/catalog.json
  collection-spec/json-schema/collection.json
  extensions/checksum/schema.json
  extensions/datacube/schema.json
  extensions/datetime-range/schema.json
  extensions/eo/schema.json
  extensions/sar/schema.json
  extensions/scientific/schema.json
  extensions/single-item/schema.json
  item-spec/json-schema/geojson.json
  item-spec/json-schema/item.json
  validation/README.md
  validation/package-lock.json
  validation/package.json
Labels: nice-to-have

#418 [STAC-417] Added href to the asset called index
  extensions/eo/example-landsat8.json
Labels: backport to stable

#419 SAR: Wrong field name used in JSON Schema + description fixes
  extensions/sar/README.md
  extensions/sar/schema.json
Labels: bug
