Repository radiantearth/stac-spec, pull requests merged in 2020-04, with the labels that each got.

#746 Proj Tweaks
  extensions/projection/README.md
  extensions/projection/examples/example-landsat8.json
  extensions/projection/json-schema/schema.json
Labels: ready for review

#704 Markdown linting
  .circleci/.remarkrc
  .circleci/config.yml
  .circleci/rc.yaml
  .gitignore
  .remarkignore
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  best-practices.md
  catalog-spec/README.md
  catalog-spec/catalog-spec.md
  collection-spec/collection-spec.md
  extensions/README.md
  extensions/asset/README.md
  extensions/checksum/README.md
  extensions/commons/README.md
  extensions/datacube/README.md
  extensions/eo/README.md
  extensions/label/README.md
  extensions/pointcloud/README.md
  extensions/projection/README.md
  extensions/sar/README.md
  extensions/scientific/README.md
  extensions/tiled-assets/README.md
  extensions/version/README.md
  extensions/view/README.md
  how-to-help.md
  implementations.md
  item-spec/README.md
  item-spec/common-metadata.md
  item-spec/examples/README.md
  item-spec/item-spec.md
  item-spec/itemcollection-spec.md
  package.json
  principles.md
  process.md
  validation/README.md
Labels: ecosystem

#776 Fix asset extension example
  extensions/asset/examples/example-landsat8.json
Labels: extension: other
